project:
  type: website
  output-dir: docs
  resources: 
    - "/assets"

website:
  title: "Kevin A Thomas"
  site-url: https://kevinathomas.com
#  google-analytics: ""
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: cv/index.qmd
        text: CV
      - href: blog/index.qmd
        text: Blog
  cookie-consent: true

format:
  html:
    theme:
      - flatly
      - darkly
    css: styles.css
    toc: true



