project:
  type: website
  output-dir: docs

website:
  title: "Kevin A Thomas"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - resume.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



