project:
  type: website
  resources:
    - ".nojekyll"
    - "img/*"
  output-dir: docs

website:
  title: "Kevin A Thomas"
  navbar:
    left:
      - href: index.qmd
        text: Home

format:
  html:
    theme: superhero
    css: styles.css
    toc: true
