project:
  type: website
  output-dir: docs

website:
  title: "Kevin A Thomas"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - resume.qmd
  cookie-consent: true

format:
  html:
    theme:
      - flatly
      - darkly
    css: styles.css
    toc: true



