---
title: "CV"
---

# Professional

## University of Pennsylvania

### Business & Data Analysis Librarian

*October 2018 - Present*

My role focuses on helping researchers find and analyze business data. That usually happens through one-on-one conversations, static support resources, and hands-on workshops. As time allows, I also enjoy improving systems and solving systemic problems in ways that expand the services the Libraries can provide:

Having observed scaling limitations in time-consuming research support tasks, I developed automated tools that dramatically increase the speed at which librarians or researchers can perform tasks such as [checking papers for known terminology](https://github.com/kevinathom/term-screener), [conducting a snowball literature search](https://github.com/kevinathom/Snowballer), or [answering a natural-language request for business research strategies](https://github.com/kevinathom/lipp-faq-rag). I provide these tools both as raw code and as executable files to support colleagues with dramatically different levels of coding comfort.

Witnessing librarians struggle to store and serve licensed data through a confusing and ineffective array of ad hoc approaches, I led cross-functional working groups in defining the problem, assessing options, recommending strategies, evaluating a solution, and recommending implementation steps. Our reports facilitated organizational leaders' decisions by clearly stating both the promises and costs of proposed solutions.

## Famous Smoke Shop

### Project Manager

*March 2018 - October 2018*

Managing the transition from in-house sales-and-inventory management software with summary-level accounting to the NetSuite enterprise resource planning platform.

Not content to complete a theoretical Master's project, I collaborated with the email marketing team and a fellow statistician to apply statistical models and present recommendations for reducing email development times.

### Marketing Analyst

*June 2015 - February 2018*

Inheriting an established affiliate marketing program, I enacted compensation, communication, promotional, and compliance initiatives, increasing the channel's rolling 12-month revenue by $933,000 (35%) with a comparable (32%) increase in profit margin.

Simultaneously, I improved transparency and accountability by designing compliance standards and conducting audits that eliminated more than $36,000 in annual waste.

## Telerx

### Operational Excellence Supervisor

*October 2013 - May 2015*

When a high-profile client asked our free-text coding process to deliver greater reliability, I led a project that improved the average reliability by about 30%-60%. As a bonus, I also developed a statistical sampling plan that would save more than $50,000 in annual quality assurance labor.

Supporting a corporate Lean Six Sigma training initiative, I personally trained more than 140 Lean Six Sigma Yellow Belts, at leadership levels from Supervisor to Director, in less than one year. After that, I automated training for a conservative projected cost reduction of at least $8,000 annually.

### Process Improvement Project Coordinator II

*February 2012 - October 2013*

When leaders were stumped for ways to help their teams work faster, they would come to me. I led observational data collection and mined large CRM datasets then analyzed both qualitative and quantitative process data in order to identify and recommend a variety of untapped efficiency and quality optimization opportunities.

I also helped Telerx achieve EHNAC accreditation by formally documenting the corporate business continuity plan and laying the groundwork for specialized site and functional area plans.

# Publication

Thomas, K. A. & Barnhart, M. E., (2021) “Research Support through Programming: Developing an Automation-Assisted Literature Search”, *Ticker: The Academic Business Librarianship Review* 6(2). doi: [https://doi.org/10.3998/ticker.1944](https://doi.org/10.3998/ticker.1944)

# Service

## The Carpentries

### Instructor

*April 2021 - Present*

Led hands-on lessons in shell, Git, SQL, and R.

## American Library Association

### BRASS Webmaster

*July 2020 - Present*

As co-webmaster for the ALA's BRASS section, I maintain Drupal site content, update the Zotero bibliography of member publications, develop new workflows, document procedures, and improve communication processes.

# Technical tools and languages

- R
- Python
- SQL
- HTML
- Excel
- Power BI

# Education

## Colorado State University

### Master of Applied Statistics

*2016 - 2018*

The program developed my foundations in a breadth of statistical techniques. My solo capstone consulting project involved [proposing an analysis plan](/assets/2018-Plan-RockSolid-KAT.pdf) for observational data collected by a 3:1 Corporate Health and Productivity Management Solutions wellness program; it concluded in [performing the analysis](/assets/2018-Analysis-RockSolid-KAT.pdf) and offering my findings as insights for the company to use in improving future wellness interventions.

## Messiah College

### Bachelor of Arts in Sociology

*2002 - 2005*

Activities and Societies:  
- AKD Honors Society
- C.N. Hostetter Jr. Fellow
- College Honors Society
- FTE Fellow
- Outreach Team Leader
- Water for the World Team Leader
